title: Brian Horlick-Cruz # your name (or website title) here
logo: "images/SAM_1680.jpg" # your photo (or logo) here
description: > #(remove <br> elements if you don't need line breaks)
  <br><br>
  Shriver Peaceworker Fellow
  MS Candidate, Geography & Environmental Systems<br>
  University of Maryland, Baltimore County<br>
  RPCV Burkina Faso, 2016-2017
  <br><br>
[Linkedin](https://www.linkedin.com/in/brian-horlick-cruz-623916197/)
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
