title: Brian Horlick-Cruz # your name (or website title) here
logo: "images/SAM_1680.jpg" # your photo (or logo) here
description: > #(remove <br> elements if you don't need line breaks)
  MS Candidate, Geography & Environmental Systems
  <br><br>
  University of Maryland, Baltimore County
  <br><br>
  https://www.linkedin.com/in/brian-horlick-cruz-623916197/
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
