title: Brian Horlick-Cruz 
logo: "images/SAM_1680.jpg" 
description: > 
  <br><br>
  Shriver Peaceworker Fellow<br>
  
  MS Candidate, Geography & Environmental Systems<br>
  University of Maryland, Baltimore County<br>
  
![Linkedin](https://www.linkedin.com/in/brian-horlick-cruz-623916197/) 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
